permalink: pretty
paginate: 9
paginate_path: "/archive/:num"

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

lsi: true
exclude:
  - Rakefile
  - tagfucker.py
  - crawl.py
  - sitelabeler.py
  - fabfile.py

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
